### ISSUE TITLE
Check wrapping on ROSplane when flying due north or due south

### ISSUE THREAD

**Issue by JMoore5353** [rosflight/rosplane#44]
Something is happening with the state estimate (maybe with the wrapping function) when flying due south. We need to figure out what is going on to cause the blips in the estimation data.

**Comment by bsutherland333** [comment]
It's only an issue when the heading passes due south. North is fine.

**Comment by iandareid** [comment]
A typo was present where the GPS course measure was supposed to be wrapped within 180 degrees of the estimated course. Instead the measure was being wrapped but directly assigned as the estimated course. This was only a when facing south because it was the only time when the two courses were further than 180 degrees from one another. 

This was fixed by commit 0bfa6c.
